export const CREATE_MODULE = 'CREATE_MODULE';
export const GET_MODULES = 'GET_MODULES';
export const GET_MODULES_ERROR = 'GET_MODULES_ERROR';
export const UPDATE_MODULE = 'UPDATE_MODULE';
export const DELETE_MODULE = 'DELETE_MODULE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const CREATE_MODULE_ERROR = 'CREATE_MODULE_ERROR';